spring:
  profiles:
    include: aws
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  server:
    url: ${SERVER_URL}

  # jwt
  jwt:
    secret: ${JWT_SECRET}
    accessToken-expire-length: 1800000   # 30분
    refresh-expire-length: 2592000000   # 1달 (30일)

logging.level:
  org.hibernate.SQL: debug