spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # jwt
  jwt:
    secret: ${JWT_SECRET}
    accessToken-expire-length: 1800000   # 30분
    refresh-expire-length: 2592000000   # 1달 (30일)

#logging.level:
#  org.hibernate.SQL: debug


cloud:
  aws:
    s3.bucket: mungdori-bucket-domain
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${AWS_S3_ACCESSKEY}
      secretKey: ${AWS_S3_SECRETKEY}